version: "3.8"

services:
  suitecrm:
    image: suitecrm:7.14.0
    build:
      context: ../
      dockerfile: ./suiteCRM/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'passwrd123'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: